# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Init.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import InfraredBallUI.UI.background_image_rc


class Ui_Init(object):
    def setupUi(self, Init):
        Init.setObjectName("Init")
        Init.resize(363, 341)
        Init.setWindowOpacity(1.0)
        Init.setAutoFillBackground(False)
        Init.setStyleSheet("background-image: url(:/Image/R.jpg);")
        self.centralwidget = QtWidgets.QWidget(Init)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 320, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background:transparent;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background:transparent;")
        self.label_2.setObjectName("label_2")
        Init.setCentralWidget(self.centralwidget)

        self.retranslateUi(Init)
        QtCore.QMetaObject.connectSlotsByName(Init)

    def retranslateUi(self, Init):
        _translate = QtCore.QCoreApplication.translate
        Init.setWindowTitle(_translate("Init", "红外反光求动作捕捉系统"))
        self.label.setText(_translate("Init", "App 初始化中，请稍等..."))
        self.label_2.setText(_translate("Init", "红外反光球动作捕捉系统"))
# import InfraredBallUI.UI.background_image_rc
